### ISSUE TITLE
DataSource issue

### ISSUE THREAD

**Issue by Ansku** [ripla/Stepper#19]
First manually entered value disappears when IntStepper is bound to a datasource that has a default value.
Steps to reproduce:

Create a new Vaadin project for 7.2.3
Add the dependency to the ivy.xml:
`<dependency org="org.vaadin.addons" name="stepper" rev="2.1.2" />`
Create a pojo with default value:
```
public class TestItem
{
	private Integer testValue = 10;

	public Integer getTestValue()
	{
		return testValue;
	}

	public void setTestValue(Integer testValue)
	{
		this.testValue = testValue;
	}
}
```
Create IntStepper and bind it to the pojo:
```
TestItem dataSource = new TestItem();
FieldGroup fieldGroup = new FieldGroup();
fieldGroup.setItemDataSource(new BeanItem<Object>(dataSource));
IntStepper testStepper = new IntStepper();
fieldGroup.bind(testStepper, "testValue");
layout.addComponent(testStepper);
```
Start server, attempt to enter '100' (gets replaced with '10'), attempt to enter '100' again (stays).
If the field isn't bound or the pojo doesn't have a default value even the first manual setting works.

**Comment by ripla** [comment]
Fixed already in 2.2.0
