### ISSUE TITLE
Format for FloatStepper

### ISSUE THREAD

**Issue by morphace** [ripla/Stepper#20]
Hi guys,

First of all: thanks for all the work you've done!

It would be nice to be able to set the decimal format of the FloatStepper, basically like with the DateStepper.

I could work on that, but I had some trouble importing the project in Intellij Idea (related to Gradle). If you could provide some hints about which IDE and settings you're using, I'll retry.

Kind regards,
Markus

**Comment by ripla** [comment]
Merged with PR #25
