### ISSUE TITLE
Declarative format support

### ISSUE THREAD

**Issue by jvmlet** [ripla/Stepper#31]
Hi
The declarative format binding fails because of java type erasure, since all steppers are generic classes.
Vaadin tries to invoke setter by type, but because of java type erasure it finds Object instead of actual Integer/BigDecimal/Float type and then passes String to
````setMinValue,setMaxValue and setStepAmount```` methods.

Would you please format the value (if ti's String) passed to each generic method  to actual type ?
Thanks.

Here is the my usage of declarative format with stepper field :
````
<!DOCTYPE html>
<html>
<head lang="en">
    <meta name="package-mapping" content="stepper:org.vaadin.risto.stepper"/>
</head>
<body>
<v-form-layout>
    <stepper-int-stepper id="maxResults" caption="Max number of results"
                         max-value="500"
                         min-value="10"
                         invalid-allowed="false"
                         required="true"
                         null-value-allowed="false"
                         step-amount="10"/>

</v-form-layout>


</body>
</html>
````

**Comment by ripla** [comment]
Fixed in 5433b70bd6aa4f16c15ed9f7aff70beb04d0bde1
