### ISSUE TITLE
[FeatureRequest] DateStepper for time

### ISSUE THREAD

**Issue by russellhoff** [ripla/Stepper#33]
I've realised that DateStepper changes only the date part, not the time. Would it be possible to make a TimeStepper?

Thank you so much!

**Comment by ripla** [comment]
Good idea. What would the data type be for the TimeStepper?

**Comment by ripla** [comment]
@russellhoff I probably should update the DateStepper for Framework/Java 8 anyways to use LocalDate, so I might as well make a counterpart that uses LocalTime. Thanks for the idea :)

**Comment by russellhoff** [comment]
You're welcome ;)
